package br.edmtool.model;

public enum KnowledgeDiagnostic {
	BAIXO_APROVEITAMENTO_GUESS, BAIXO_APROVEITAMENTO_SLIP, BAIXO_APROVEITAMENTO_UNKONW, 
    ALTO_APROVEITAMENTO_GUESS, ALTO_APROVEITAMENTO_SLIP, ALTO_APROVEITAMENTO_UNKONW, 
    PERDA_APROVEITAMENTO_GUESS, PERDA_APROVEITAMENTO_SLIP, PERDA_APROVEITAMENTO_UNKONW
}
